-- ADR-004 §5.3 subscriptions, §5.4 payments, §5.6 shedlock.

CREATE TABLE subscriptions (
    id          uuid        PRIMARY KEY,
    user_id     uuid        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    product_id  uuid        NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
    plan_id     uuid        NOT NULL,
    status      varchar(16) NOT NULL,
    start_date  timestamptz NOT NULL,
    end_date    timestamptz NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT subscriptions_status_check CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT subscriptions_dates_check CHECK (end_date >= start_date),
    CONSTRAINT subscriptions_user_product_uq UNIQUE (user_id, product_id),
    CONSTRAINT subscriptions_plan_fk FOREIGN KEY (plan_id, product_id) REFERENCES plans (id, product_id) ON DELETE RESTRICT
);
CREATE INDEX subscriptions_active_end_idx ON subscriptions (end_date) WHERE status = 'ACTIVE';
CREATE INDEX subscriptions_product_status_idx ON subscriptions (product_id, status);
CREATE INDEX subscriptions_plan_idx ON subscriptions (plan_id, product_id);

CREATE TABLE transactions (
    id                      uuid         PRIMARY KEY,
    order_id                varchar(40)  NOT NULL,
    user_id                 uuid         NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    product_id              uuid         NOT NULL,
    plan_id                 uuid         NOT NULL,
    subscription_id         uuid         REFERENCES subscriptions (id) ON DELETE RESTRICT,
    amount                  bigint       NOT NULL,
    currency                char(3)      NOT NULL DEFAULT 'IDR',
    billing_period          varchar(16)  NOT NULL,
    status                  varchar(16)  NOT NULL DEFAULT 'PENDING',
    payment_method          varchar(32),
    gateway_transaction_id  varchar(64),
    snap_token              varchar(64),
    snap_redirect_url       text,
    snap_expires_at         timestamptz,
    failure_reason          text,
    needs_review            boolean      NOT NULL DEFAULT false,
    idempotency_key         uuid,
    paid_at                 timestamptz,
    created_at              timestamptz  NOT NULL DEFAULT now(),
    updated_at              timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT transactions_order_id_uq UNIQUE (order_id),
    CONSTRAINT transactions_idempotency_uq UNIQUE (user_id, idempotency_key),
    CONSTRAINT transactions_amount_check CHECK (amount > 0),
    CONSTRAINT transactions_billing_period_check CHECK (billing_period IN ('MONTHLY', 'YEARLY')),
    CONSTRAINT transactions_status_check CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')),
    CONSTRAINT transactions_payment_method_check CHECK (
        payment_method IS NULL
        OR payment_method IN ('QRIS', 'BANK_TRANSFER', 'GOPAY', 'SHOPEEPAY', 'CREDIT_CARD', 'OTHER')
    ),
    CONSTRAINT transactions_paid_at_check CHECK (status <> 'PAID' OR paid_at IS NOT NULL),
    CONSTRAINT transactions_plan_fk FOREIGN KEY (plan_id, product_id) REFERENCES plans (id, product_id) ON DELETE RESTRICT
);
CREATE INDEX transactions_user_created_idx ON transactions (user_id, created_at DESC);
CREATE INDEX transactions_user_plan_pending_idx ON transactions (user_id, plan_id) WHERE status = 'PENDING';
CREATE INDEX transactions_created_idx ON transactions (created_at DESC);
CREATE INDEX transactions_product_status_created_idx ON transactions (product_id, status, created_at);
CREATE INDEX transactions_needs_review_idx ON transactions (created_at) WHERE needs_review;
CREATE INDEX transactions_subscription_idx ON transactions (subscription_id);
CREATE INDEX transactions_plan_product_idx ON transactions (plan_id, product_id);

CREATE TABLE transaction_status_history (
    id               bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id   uuid         NOT NULL REFERENCES transactions (id) ON DELETE RESTRICT,
    from_status      varchar(16),
    to_status        varchar(16)  NOT NULL,
    source           varchar(16)  NOT NULL,
    note             text,
    gateway_payload  jsonb,
    created_at       timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT tsh_source_check CHECK (source IN ('CHECKOUT', 'WEBHOOK', 'SYNC'))
);
CREATE INDEX tsh_transaction_created_idx ON transaction_status_history (transaction_id, created_at);

-- Standard ShedLock table (ADR-002 rule S2).
CREATE TABLE shedlock (
    name        varchar(64)  PRIMARY KEY,
    lock_until  timestamptz  NOT NULL,
    locked_at   timestamptz  NOT NULL,
    locked_by   varchar(255) NOT NULL
);
